version: "3.9"

services:
  postgresql:
    image: postgres:14.2-bullseye
    container_name: vixtract_postgresql
    restart: always
    tty: true
    stdin_open: true
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=vixtract
    volumes:
     - postgresql:/var/lib/postgresql/data

  jupyter:
    image: vixtract/jupyter:2.0
    container_name: vixtract_jupyter
    restart: always
    tty: true
    stdin_open: true
    volumes:
     - jupyter-libs:/usr/local/lib/python3.10/dist-packages
     - jupyter-home:/home
     - jupyter-config:/app
     - jupyter-etc:/etc

  cronicle:
    image: vixtract/cronicle:2.0
    container_name: vixtract_cronicle
    hostname: vixtract_primary-cronicle-server # lock container hostname for Cronicle server connect
    restart: always
    depends_on:
      - jupyter # for shared volumes
    volumes:
      - cronicle-data:/opt/cronicle/data
      #- /var/lib/docker/volumes/vixtract_jupyter-libs/_data:/usr/local/lib/python3.10/dist-packages:ro
      - jupyter-home:/opt/cronicle/jupyter-home
      - jupyter-libs:/usr/local/lib/python3.10/dist-packages:ro

  nginx:
    image: vixtract/nginx:2.0
    container_name: vixtract_nginx
    restart: always
    depends_on:
      - jupyter
      - cronicle
      - postgresql
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-etc:/etc/nginx
      - nginx-www:/var/www

volumes:
  postgresql:
  jupyter-config:
  jupyter-home:
  jupyter-etc:
  jupyter-libs:
  cronicle-data:
  nginx-etc:
  nginx-www:
