FROM ubuntu:22.04

WORKDIR /app

# Update and Python install
RUN apt-get update -y && apt-get install -y python3-pip && pip3 install --upgrade pip

# Install NodeJS and proxy
RUN apt-get install npm nodejs -y && \
    npm install -g configurable-http-proxy

# Jupyter installation
RUN pip3 install jupyterhub && \
    pip3 install jupyterlab && \
    pip3 install --upgrade notebook

# Add essential libs
RUN pip3 install pandas scipy matplotlib wheel ipywidgets papermill petl && \
    pip3 install "dask[distributed,dataframe]" && \   
    pip3 install dask_labextension
RUN pip3 install jupyterhub-nativeauthenticator

# Add default admin user
RUN useradd admin && echo admin:vixtract | chpasswd
RUN mkdir /home/admin && chown admin:admin /home/admin

# Copy configs and scripts
ADD ./jupyterhub_config.py /app
ADD ./create-user.py /app

# Volumes for keeping new users, Python libs
VOLUME /app
VOLUME /home
# VOLUME /etc/passwd
# VOLUME /etc/shadow
# VOLUME /usr

EXPOSE 8000

ENTRYPOINT ["jupyterhub", "--ip=0.0.0.0", "--port=8000", "--no-ssl"]


